backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - label: "Produits"
    name: "product"
    folder: "src/products"
    create: true
    identifier_field: "name"
    fields:
      - { label: "Id", name: "id", widget: "number" }
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Prix", name: "price", widget: "number" }
      - {
          label: "Date de publication",
          name: "publish_date",
          widget: "datetime",
        }
